# Generated by Django 5.1.5 on 2025-01-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter your name', max_length=50)),
                ('email', models.EmailField(help_text='Enter Email', max_length=254, unique=True)),
                ('emp_joing_date', models.DateTimeField(auto_now_add=True)),
                ('emp_updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.CharField(help_text='Enter your details', max_length=100)),
                ('phone', models.IntegerField(help_text='Enter your number')),
                ('emp_start_time', models.TimeField()),
                ('gender', models.CharField(max_length=10)),
                ('emp_dob', models.DateTimeField()),
                ('emp_active', models.BooleanField()),
                ('password', models.CharField(max_length=16)),
                ('profile_pic', models.ImageField(upload_to='image/')),
                ('resume', models.FileField(upload_to='file/')),
            ],
        ),
    ]
